version: '3.3'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    ports:
      - '3000:3000'
    networks:
      - covercraft_network

  generation-service:
    build: 
      context: ./generation-service
      dockerfile: Dockerfile
    container_name: generation-service
    restart: always
    volumes:
      - ./generation-service/app:/code/app
    ports:
      - '8000:8000'
    env_file:
      - ./secret/.env
    networks:
      - covercraft_network

networks:
  covercraft_network:
    external: true
    