version: '3.9'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - '3000:3000'
    networks:
      - covercraft_network

networks:
  covercraft_network:
    external: true
    