version: '3.9'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - '8080:8080'
    networks:
      - covercraft_network


networks:
  covercraft_network:
    driver: bridge